TARGET_ARCH := arm
TARGET_ARCH_VARIANT := armv7-a
TARGET_CPU_ABI := armeabi-v7a
TARGET_CPU_ABI2 := armeabi
TARGET_CPU_VARIANT := cortex-a7
TARGET_BOARD_PLATFORM := lc1860
TARGET_BOOTLOADER_BOARD_NAME := lc1860

BOARD_KERNEL_CMDLINE := console=ttyS0,115200n8 androidboot.hardware=lc1860c
BOARD_KERNEL_BASE := 0x00000000
BOARD_KERNEL_PAGESIZE := 2048

TARGET_RECOVERY_FSTAB := device/xiaomi/hm2a/recovery.fstab
TARGET_RECOVERY_PIXEL_FORMAT := RGBX_8888
TARGET_USERIMAGES_USE_EXT4 := true
BOARD_HAS_NO_SELECT_BUTTON := true

RECOVERY_VARIANT := philz

# 减体积
PHILZ_NO_AROMAFM := true
PHILZ_NO_FB2PNG := true
TW_NO_NTFS := true
TW_NO_EXFAT := true